# ===========================================
# ORION AUTH SERVICE - Gateway Integration
# Auth Service se comunica a través del Gateway
# ===========================================

server:
  port: ${AUTH_SERVICE_PORT:8091}

spring:
  application:
    name: ${AUTH_SERVICE_NAME:orion-auth}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI}

  # Google OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email,profile

# JWT Configuration
jwt:
  algorithm: ${JWT_ALGORITHM:RS256}
  issuer: ${JWT_ISSUER:orion-auth}
  audience: ${JWT_AUDIENCE:orion-services}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400}

# External API URLs (no cambian - van directo)
api:
  student:
    url: ${STUDENT_API_URL}
  actor:
    url: ${ACTOR_API_URL}

# Service URLs - AHORA VAN AL GATEWAY
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8080/api/users}

role:
  service:
    url: ${ROLE_SERVICE_URL:http://localhost:8080/api/roles}

program:
  service:
    url: ${PROGRAM_SERVICE_URL:http://localhost:8080/api/programs}

# Gateway configuration
gateway:
  url: ${GATEWAY_URL:http://localhost:8080}
  service:
    token: ${GATEWAY_SERVICE_TOKEN:auth-service-token-secure-2025}

# Logging Configuration - Debug para troubleshooting
logging:
  level:
    com.unibague.gradework: ${LOG_LEVEL_AUTH:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.springframework.web.client: DEBUG
    root: ${LOGGING_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

---
# ===========================================
# DOCKER PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: docker

# Docker URLs - Auth Service sigue usando Gateway
user:
  service:
    url: http://orion-gateway:8080/api/users

role:
  service:
    url: http://orion-gateway:8080/api/roles

program:
  service:
    url: http://orion-gateway:8080/api/programs

gateway:
  url: http://orion-gateway:8080